### ISSUE TITLE
@distube/ytdl-core WARNING: Could not parse decipher function.

### ISSUE THREAD

**Issue by thefu21** [museofficial/muse#1238]
Since today (March 24, 2025), music playback is no longer working. Errors occur when starting the bot, which seem to be related to processing stream URLs.

Error Messages:

    WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".

    WARNING: Could not parse decipher function. Stream URLs will be missing.

    WARNING: Could not parse n transform function.

It seems there's an issue with the YTDL-Core module that prevents the bot from streaming music. I'm being warned about missing stream URLs, and while I was advised to update the library, the errors persist even after the update.

Steps to Reproduce:

    Start the bot.

    Attempt to play music.

    Errors occur, and music playback fails.

Expected Behavior: Music should play as expected without errors.

Version: 2.10.1 (built on January 29, 2025)

Here are my logs:

    Running version 2.10.1 built on 1/29/2025 (commit d7f0a954e2f0456e61018d7df75cebcdb09e3c2a)
    
    🔧 Need help? https://github.com/codetheweb/muse/discussions/new
    
    🐛 Bug? https://github.com/codetheweb/muse/issues/new
    
    ✨ New feature? https://github.com/codetheweb/muse/issues/new
    
    ☕ Discussion? https://github.com/codetheweb/muse/discussions/new
    
    💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb

    - Applying database migrations...

    ✔ Database migrations applied.

    - 📡 connecting to Discord...
    
    ✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=1296556295792496703&scope=bot%20applications.commands&permissions=36700160
    
    WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
    
    WARNING: Could not parse decipher function.
    
    Stream URLs will be missing.
    
    Please report this issue with the "1742838634328-base.js" file on https://github.com/distubejs/ytdl-core/issues/144.
    
    WARNING: Could not parse n transform function.
    
    Please report this issue with the "1742838634630-base.js" file on https://github.com/distubejs/ytdl-core/issues/144.

**Comment by GamerGuy95953** [comment]
Having same issue. :(

WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse decipher function.
Stream URLs will be missing.
Please report this issue with the "1742863799234-base.js" file on https://github.com/distubejs/ytdl-core/issues/144.
WARNING: Could not parse n transform function.
Please report this issue with the "1742863799438-base.js" file on https://github.com/distubejs/ytdl-core/issues/144.

**Comment by naseer-rehman** [comment]
Having same issue with the same log

**Comment by ayazlockhat** [comment]
Having same issue with the same log

**Comment by pashalecqua** [comment]
same issue here with same log and steps to reproduce

**Comment by volktron** [comment]
Having same issue with the same log

**Comment by ChrisTecha** [comment]
Having same issue with the same log

**Comment by thefu21** [comment]
I think this pr probably fixes the bug https://github.com/IvanMicai/muse/tree/update-ytdl-core

**Comment by Duckyz95** [comment]
Can confirm, updating ytdl-core fixes the issue

**Comment by thefu21** [comment]
I tried updatig ytdl-core but it didn't fix the issue for me, so it is probably a ytdl issue many people are reporting the same issue here: https://github.com/distubejs/ytdl-core/issues/144

**Comment by Duckyz95** [comment]
What I did was `npm audit fix` followed by `npm install @distube/ytdl-core@latest` and it now works

**Comment by NathanGilbert2** [comment]
I got this to work, but only for regular YouTube videos. Anytime I tried to use live YouTube videos like [Doom Radio](https://www.youtube.com/watch?v=JEuAYnjtJP0) it would fail with the `transform function` error. I would have to restart the container for it to work again after that.

```yml
version: '3.4'

services:
  muse:
    image: ghcr.io/museofficial/muse:2.10.1
    restart: always
    environment:
      - DISCORD_TOKEN=<OBFUSCATED>
      - YOUTUBE_API_KEY=<OBFUSCATED>
      - SPOTIFY_CLIENT_ID=<OBFUSCATED>
      - SPOTIFY_CLIENT_SECRET=<OBFUSCATED>
    volumes:
      - type: volume
        source: muse
        target: /data
        read_only: false
    entrypoint: >
      /bin/sh -c "npm i --package-lock-only && npm audit fix --force && npm install @distube/ytdl-core@latest && exec tini -- node --enable-source-maps dist/scripts/migrate-and-start.js"
volumes:
  muse:
```
