### ISSUE TITLE
Muse does not function

### ISSUE THREAD

**Issue by slaapkopamy** [museofficial/muse#1258]
**What's happening?**
I recently setup a clean installation of muse using docker compose file pulling the latest version (2.11.1), I inserted the api keys for youtube and spotify in the bot with ofcourse my bot token. started the bot up and invited the bot in my server. now i wanted to test the functionality of the bot by adding a spotify url in the play command to findout it's getting errored with ope: song not found, tried with a different url.. same thing. tried with just searching... guess what... same thing...
if i try with a youtube url i get 403 forbidden (probably something on google side since i cant access the api key on my pc either)

**Logs**
For some reason, there are no logs being produced in the docker container. if i run docker compose logs -f the only last thing i see is the discord invite url for the bot.

**Screenshots**
discord: https://slaapkopamy.com/sc/images/lJoRssyXbJ8FXjBr8SY4z.png
docker: https://slaapkopamy.com/sc/images/Y3NrZ4SoFvrCgdysphmkC.png

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.11.1
- Docker (if applicable): 28.0.4 build v8034c0
- OS: ubuntu 20.4.6 lts
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by melzyy** [comment]
try #1255

**Comment by slaapkopamy** [comment]
> try [#1255](https://github.com/museofficial/muse/issues/1255)

Sadly tried and same issue, also the docker container does not produce any logs

**Comment by a-sitarz** [comment]
Got the same issue.
Looks like YT changed something, again...

**Comment by nealhead** [comment]
Are we done for? Do any self hosted music bots still work?

**Comment by JordiBrisbois** [comment]
Dirty fix while waiting for [this pull request](https://github.com/distubejs/ytdl-core/pull/251) to be merged.

If you're using Docker, mount /usr/ as a volume:

```
services:
  muse:
    image: 'ghcr.io/museofficial/muse:pr-1256'
    restart: always
    volumes:
      - 'bot-data-muse:/data'
      - 'bot-datanode-muse:/usr/'
    environment:
      - DISCORD_TOKEN=xxx
      - YOUTUBE_API_KEY=xxx
      - SPOTIFY_CLIENT_ID=xxx
      - SPOTIFY_CLIENT_SECRET=xxx
volumes:
  bot-data-muse: null
  bot-datanode-muse: null
```
Next, edit /app/node_modules/@distube/ytdl-core/lib/sig.js inside the container and replace its contents with the code from:

https://raw.githubusercontent.com/distubejs/ytdl-core/ba7516dd4f5ad125f9ee8a41ebea486442533f82/lib/sig.js

Save the file, restart your container, and it should work.
